$webXmlPath = './Web.config'; 
$xml = ((Get-Content $webXmlPath) -as [Xml]); 
$xml.get_DocumentElement()['system.web'].compilation.debug = if($env:DEBUG -ne $null) {"$env:DEBUG"} else {"false"};
($xml.get_DocumentElement().appSettings.add | Where-Object { $_.Key -eq 'ambiente' }).value = "$env:AMBIENTE";
($xml.get_DocumentElement().appSettings.add | Where-Object { $_.Key -eq 'LDAPQueryFilter' }).value = "$env:LDAPQUERYFILTER";
($xml.get_DocumentElement().appSettings.add | Where-Object { $_.Key -eq 'gravarEmailEmArquivo' }).value = "$env:GRAVAREMAILEMARQUIVO";
($xml.get_DocumentElement().appSettings.add | Where-Object { $_.Key -eq 'caminhoArquivoEmail' }).value = "$env:CAMINHOARQUIVOEMAIL";
($xml.get_DocumentElement().appSettings.add | Where-Object { $_.Key -eq 'modificarAssuntoConformeAmbiente' }).value = "$env:MODIFICARASSUNTOCONFORMEAMBIENTE";
($xml.get_DocumentElement().appSettings.add | Where-Object { $_.Key -eq 'ida:ADFSMetadata' }).value = "$env:ADFSREALM"; 
($xml.get_DocumentElement().appSettings.add | Where-Object { $_.Key -eq 'ida:Wtrealm' }).value = "$env:WTREALM"; 
($xml.get_DocumentElement().appSettings.add | Where-Object { $_.Key -eq 'ida:Wreply' }).value = "$env:ADFSREPLY"; 
($xml.get_DocumentElement().appSettings.add | Where-Object { $_.Key -eq 'SIGRHAPI' }).value = "$env:SIGRHAPI";
($xml.get_DocumentElement().appSettings.add | Where-Object { $_.Key -eq 'URL_PGD' }).value = "$env:URLPGD"; 
($xml.get_DocumentElement().appSettings.add | Where-Object { $_.Key -eq 'DiretorioArquivos' }).value = "$env:DIRARQUIVOS"; 
($xml.get_DocumentElement().appSettings.add | Where-Object { $_.Key -eq 'IPLDAP' }).value = "$env:LDAPIP"; 
($xml.get_DocumentElement().appSettings.add | Where-Object { $_.Key -eq 'PortaLDAP' }).value = "$env:LDAPPORT"; 
($xml.get_DocumentElement().appSettings.add | Where-Object { $_.Key -eq 'habilitarTratamentoBancoReplicado' }).value = "$env:HABILITARTRATAMENTOBANCOREPLICADO";
($xml.get_DocumentElement().appSettings.add | Where-Object { $_.Key -eq 'NetworkCredentialLDAP' }).value = "$env:NETWORKCREDENTIALLDAP";
($xml.get_DocumentElement().connectionStrings.add |  Where-Object { $_.Name -eq 'PGDConnectionString' }).connectionString = "$env:PGDCONNECTIONSTRING"
$xml.get_DocumentElement()['system.net'].mailSettings.smtp.from = "$env:SMTPFROM"; 
$xml.get_DocumentElement()['system.net'].mailSettings.smtp.network.host = "$env:SMTPHOST"; 
$xml.get_DocumentElement()['system.net'].mailSettings.smtp.network.port = "$env:SMTPPORT"; 
$xml.get_DocumentElement()['system.net'].mailSettings.smtp.network.defaultCredentials = "$env:USEDEFAULTCREDENTIALS"; 
$xml.get_DocumentElement()['system.net'].mailSettings.smtp.network.userName = "$env:SMTPUSERNAME"; 
$xml.get_DocumentElement()['system.net'].mailSettings.smtp.network.password = "$env:SMTPPASSWORD"; 
$xml.get_DocumentElement().nlog.targets.target.connectionString = "$env:PGDCONNECTIONSTRING"; 
$xml.get_DocumentElement().nlog.rules.logger.levels = "$env:NIVEISLOG";
$xml.Save($webXmlPath);
Write-Host "Programa de Gestao do Cade";
& C:/ServiceMonitor.exe w3svc;